export const TOKEN_VALID       = "TOKEN_VALID";
export const TOKEN_INVALID     = "TOKEN_INVALID";
export const AUTHENTICATE      = "AUTHENTICATE";
export const AUTHENTICATE_FAIL = "AUTHENTICATE_FAIL";

export const NAVIGATE_TO_MAIN = "NAVIGATE_TO_MAIN";
