// nav
export const NAVIGATE_TO_MAIN        = "NAVIGATE_TO_MAIN";
export const NAVIGATE_TO_GAMES       = "NAVIGATE_TO_GAMES";
export const NAVIGATE_TO_LEADERBOARD = "NAVIGATE_TO_LEADERBOARD";
export const NAVIGATE_TO_TEAMS       = "NAVIGATE_TO_TEAMS";
export const NAVIGATE_TO_SETTINGS    = "NAVIGATE_TO_SETTINGS";

// errors
export const DISMISS_ERRORS   = "DISMISS_ERRORS";

// auth
export const VALIDATING_TOKEN         = "VALIDATING_TOKEN";
export const VALIDATING_TOKEN_FAIL    = "VALIDATING_TOKEN_FAIL";
export const VALIDATING_TOKEN_SUCCESS = "VALIDATING_TOKEN_SUCCESS";
export const SIGNING_IN         = "SIGNING_IN";
export const SIGNING_IN_FAIL    = "SIGNING_IN_FAIL";
export const SIGNING_IN_SUCCESS = "SIGNING_IN_SUCCESS";
export const SIGNING_UP         = "SIGNING_UP";
export const SIGNING_UP_FAIL    = "SIGNING_UP_FAIL";
export const SIGNING_UP_SUCCESS = "SIGNING_UP_SUCCESS";
export const SIGNING_OUT        = "SIGNING_OUT";
